ITEMS = [
    "hierro", "cobre", "oro", "plata", "silicio", "carbono", "uranio", "titanio",
    "cobalto", "litio", "plomo", "estaño", "aluminio", "magnesio", "nitrogeno", "oxigeno",
    "hidrogeno", "agua", "sal", "azufre", "fosforo", "gasolina", "materia oscura",
    "combustible ionico", "antimateria", "deuterio", "celulas de energia",
    "baterias", "martillo", "destornillador", "taladro", "llave inglesa",
    "soldador", "cortador laser", "pico minero", "sierra circular", "grua portatil",
    "kit de reparaciones", "computadora portatil", "multimetro", "impresora 3D",
    "pistola laser", "rifle de plasma", "cañon gauss", "lanza misiles",
    "espada de energia", "granada", "arco gravitacional", "cuchillo de vibracion",
    "granada de humo", "torreta automatica", "reliquia antigua", "amuleto de poder",
    "estatua alienigena", "cubo misterioso", "libro prohibido", "esfera luminosa",
    "fragmento de meteorito", "antiguo chip", "calavera cristal", "moneda historica",
    "mapa estelar antiguo", "comida enlatada", "semillas", "ropa de recambio",
    "botiquin", "medicinas", "herramientas de laboratorio", "escaner",
    "modulo de comunicaciones", "radio", "sensores termicos", "motor de curvatura",
    "generador de escudos", "nano-bots", "sistema de navegacion",
    "drones de reparacion", "chips de IA", "sistema de camuflaje", "propulsores",
    "paneles solares", "reactor nuclear", "sensor de radiacion", "rastreador",
    "transmisor cuantico", "cristales de energia", "cores de fusion",
    "barras de titanio", "placas de circuito", "conductores superconductores",
    "bobina magnetica", "microchips", "modulo de mineria", "raciones de emergencia",
    "bebidas energeticas", "barriles vacios", "capsula de escape",
    "material aislante", "antorcha", "bateria portatil", "kit de supervivencia",
    "equipo de escalada", "explosivos", "motosierra", "dispositivo holografico",
    "cristal quantico", "repuesto de casco", "sensor de presion",
    "material de construccion", "cableado", "conductos", "compresor de aire",
    "modulo de terraformacion", "contenedor criogenico", "nanofibras",
    "materia prima generica", "muestras biologicas", "compuesto quimico",
    "fuente de protones",
]
